# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 805edb640559cb35318a7a3805497e1169f7c597bf4261f87862861c901d615cf4ca0cb4ab55e4980556e606383c8c41cc7f45e994efc1f74582c06642e65c08
  FBid: <%= ENV["FBid"] %>
  FBsecret: <%= ENV["FBsecret"] %>

test:
  secret_key_base: eca95d0c949735c97c310c1c4404de94d6eb1c764459dad35e60dac828c029039907b33ec33a02e3ae19d9d9b0c222e94105d569600d7494c2aea87b740ffbae
  FBid: <%= ENV["FBid"] %>
  FBsecret: <%= ENV["FBsecret"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FBid: <%= ENV["FBid"] %>
  FBsecret: <%= ENV["FBsecret"] %>
